//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class coursetimetable
    {
        public int coursetimetable1 { get; set; }
        public string coursename { get; set; }
        public string clustername { get; set; }
        public string teachername { get; set; }
        public string room { get; set; }
        public string days { get; set; }
        public string time { get; set; }
        public Nullable<int> courseId { get; set; }
        public Nullable<int> locationId { get; set; }
    
        public virtual course course { get; set; }
        public virtual courselocation courselocation { get; set; }
    }
}
