//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class courseclusterunit
    {
        public int courseId { get; set; }
        public int clusterId { get; set; }
        public int unitId { get; set; }
    
        public virtual course course { get; set; }
        public virtual unit unit { get; set; }
        public virtual cluster cluster { get; set; }
    }
}
