//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incoursesemester
    {
        public int inlocationcourse { get; set; }
        public int courseId { get; set; }
        public int semesterId { get; set; }
    
        public virtual course course { get; set; }
        public virtual coursesemester coursesemester { get; set; }
    }
}
